#spring:
#  mail:
#    # ?? SMTP ?????
#    host: smtp.qq.com
#    # ?????
#    username: 756624050@qq.com
#    # ??????????????????????????
#    # POP3 cxtfolvvqdzjbegf
#    # IMAP byxdxkbpkcnwbdbf
#
#    password: cxtfolvvqdzjbegf
#    # ???465?587
#    port: 587
#    # ????????UTF-8
#    default-encoding: UTF-8
#    # ??SSL ????
#    properties:
#      mail:
#        smtp:
#          socketFactoryClass: jakarta.net.ssl.SSLSocketFactory
#        #???? DEBUG ???????????????????????????????
#        debug: true

config.path： E:\\ideaDownload\\springbootMtools\\javaMail2\\src\\main\\resources\\emailConfig.properties