server:
  port: 8088

spring:
  application:
    name: webdemo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.3.228:1521/ORCLPDB
    username: TOSOFILE
    password: softroad

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.softroad.testdbdemo.mapper
  mapper-locations: classpath:mapper/*.xml